name: Keep Supabase Alive

on:
  schedule:
    # รันทุกวันจันทร์และพฤหัสบดี เวลา 00:00 UTC
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # ปุ่มกดรันเองเพื่อทดสอบ

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/posts?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
